name: backend-api-deploy-vercel

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm install || true

      - name: install vercel cli
        run: npm install -g vercel

      - name: deploy to vercel
        run: vercel deploy --prod --yes --token=${{ secrets.VERCEL_SECRETS }}
   
